// require('./01.maopao.js')
// require('./02.xuanze')
// require('./03.charu')
// require('./04.xier')
// require('./05.guibing')
require('./06.kuaisu')
// require('./07.jishu')
// require('./08.tong')
// require('./09.jishu')
